### ISSUE TITLE
Замечание по СРС 1 по курсу СУБД

### ISSUE THREAD

**Issue by ns-roxer** [go-park-mail-ru/2023_2_Holi#6]
1. https://github.com/go-park-mail-ru/2023_2_Holi/tree/dev/db/migrations/code - зачем триггеры положили отдельно от файлов миграции, создающих эти таблицы. Сильно усложняет чтение кода
2. varchar без ограничения по длине замените на text.
3. varchar с ограничением по длине у меня вызывает большие сомнения. Например у юзера name и image_path легко могут стать больше 100 символов. Либо замените все  varchar(N) на текст, либо рядом комментарием к каждому полю допишите причину именно такого размера.
4. у таблиц video_cast, video_estimation, video_genre, video_tag явно не описаны primary key, просто замените unique на primary key и отразите это в er диаграмме

**Comment by ellexo2456** [comment]
1 Сделал так, потому что это рекомендовано в документации: https://github.com/jackc/tern#code-packages
но, в данной ситуации это наверное действительно неоправданно, переделал

4 Зачем каждой таблице обязательно нужен pk? И насколько было бы правильно добавить в эти таблицы суррогатный ключ?

**Comment by ns-roxer** [comment]
1. У вас там триггеры, а не функции. Когда открываешь файл с добавлением таблицы, очень удобно сразу видеть, какие триггеры могут сработать при изменении этой таблицы. А вот функции действительно стоит выносить в отдельные файлы, так как если функция хорошо названа, не обязательно заглядывать в ее код, чтобы понять зачем она тут и что делает
4. У вас в этих таблицах явно заданы unique ключи. Изучите, чем primary key, отличается от unique. Я указываю на то, что оба этих constraint проверяют уникальность и я искренне не понял мотивации по добавлению unique вместо PK

**Comment by ellexo2456** [comment]
понял, спасибо
